### ISSUE TITLE
module 'tinyik' has no attribute 'visualize'

### ISSUE THREAD

**Issue by OdevarJr** [lanius/tinyik#12]
Hello. I'm trying to run the examples with visualization feature, as shown in Readme.md. But I'm having the following error message: 
**module 'tinyik' has no attribute 'visualize'**

In fact,  "visualize" function was not found at tinyik code.

P.S.: I've installed the package using the command "pip install tinyik[viz]" at cmd. During installation, I've received the following:
**WARNING: tinyik 1.2.0 does not provide the extra 'viz'**

How to get the visualization feature? I'm using Python 3.8.3 over Windows 10 64bits.

**Comment by lanius** [comment]
I was able to reproduce it in my environment as well.

The visualization feature was added in version 2.0.0, but for some reason it seems to install the older version of tinyik. As a temporary workaround, try installing the latest version of tinyik and open3d as follows. (At the moment, viz extra just installs open3d additionally.)

```
pip install tinyik -U
pip install open3d
```

**Comment by OdevarJr** [comment]
Hello, Ianius. Thank you very much!

Installing again as you showed, now is working!

You're right about the version. When installed without the "-U" statement, the version was tinyik-1.2.0. But with "-U" statement, the version now is tinyik-2.1.0.

P.S.: As my testing machine is an old HP Elitebook (with Intel HD3000 graphics), I need to install and configure MESA: [https://github.com/pal1000/mesa-dist-win/releases](url)
For Windows 10 64-bit, choose "mesa3d-20.3.2-release-mingw.7z"

As it`s solved, I will close the issue. Thanks again.

Regards!
