### ISSUE TITLE
Links that run along the Z-axis aren't shown in the visualizer

### ISSUE THREAD

**Issue by satej1210** [lanius/tinyik#18]
Hello!

First off, this project is awesome! The fact that is it so simple and the code is easy to understand is great.

The problem I have is that when some links are drawn along the Z-axis, the cylinders aren't displayed in the visualizer.

Here's the configuration I'm working with:
```
tinyik.Actuator(['z', [0, 0, 180.7], 'y', [-612.7, 0, 0], 'y', [-571.55, 0, 0], 'y', [0, -174.15, 0], 'z', [0, 0, -119.85], 'y', [0, -116.55, 0]])
```
Here's a screenshot from the visualizer:
![Screenshot (107)](https://user-images.githubusercontent.com/6539210/122682624-34852880-d1c0-11eb-9372-a2ff4f1ce20b.png)

(FYI, I'm using a radius of 10)

Do you know of a workaround for this problem?

Thanks!

**Comment by satej1210** [comment]
I forgot to include that there is also a `RuntimeWarning` that is printed when opening the visualizer:
```
 <environment_dir>\lib\site-packages\tinyik\visualizer.py:85: RuntimeWarning: invalid value encountered in true_divide
  axis = cross / np.linalg.norm(cross)
```

**Comment by lanius** [comment]
Thanks for the nice pull request! I've merged it as a bug fix.
